Make sword on Ender Chest/Chest being enchanted when you already put it on them
tomkeuper/BedWars1058 pull request #286
Opened 2024-05-26 10:07 UTC by SunshroomChan

More like Hypixel so i would like to add this instead when you get enchanted so you will gonna not get enchanted when on that 
Video: https://drive.google.com/file/d/1wLE6mw79uJNv94UCRkOjbN7QNVw5YvJl/view?usp=sharing

2024-06-03 22:46 UTC, tomkeuper approved these changes

2024-06-03 22:54 UTC, tomkeuper commented
You forgot to commit the import of `InventoryOpenEvent`. Once that is done we can merge this

2024-06-03 22:54 UTC, tomkeuper requested changes
import of InventoryOpenEvent needed

2024-06-04 01:05 UTC, SunshroomChan commented
> import of InventoryOpenEvent needed

okay, let’s me see it

2024-06-04 22:39 UTC, tomkeuper approved these changes

2024-06-04 22:39 UTC, merged