fix block protection
tomkeuper/BedWars1058 pull request #83
Opened 2023-05-02 06:46 UTC by ImYenil

Fixed bug with shop protection and upgrades protection not working

2023-05-02 18:10 UTC, tomkeuper approved these changes

2023-05-04 20:27 UTC, tomkeuper requested changes

2023-05-04 20:27 UTC, tomkeuper commented on bedwars-api/src/main/java/com/andrei1058/bedwars/api/configuration/ConfigPath.java
> +    public static final String ARENA_CONFIGURATION_MIN_BUILD_Y = "min-build-y";
There are already config paths for min and max build height. Make sure to use an up to date branch

2023-05-04 20:55 UTC, KKiiya approved these changes
Test

2023-05-04 23:18 UTC, ImYenil commented on bedwars-api/src/main/java/com/andrei1058/bedwars/api/configuration/ConfigPath.java
> +    public static final String ARENA_CONFIGURATION_MIN_BUILD_Y = "min-build-y";
Yes, I know, but my project does not have all the contents applied. What should I do?

2023-05-05 14:20 UTC, closed without merging